package guiutmedic.formularios;

import guiutmedic.clases.ConexionBD;
import guiutmedic.clases.Usuario;
import guiutmedic.clases.UsuarioBD;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**AAAA
 *
 * @author santi
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLoginUusario
     */
    boolean pressedUsuario = false;
    boolean pressedPass = false;

    public frmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backround = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblContraseña = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);

        backround.setBackground(new java.awt.Color(252, 252, 252));
        backround.setToolTipText("");
        backround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenido.setFont(new java.awt.Font("Inter", 3, 14)); // NOI18N
        lblBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenido.setText("Bienvenido");
        backround.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 90, 30));

        lblIcono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiutmedic/imagenes/iconoLogin.jpeg"))); // NOI18N
        backround.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 280, 250));

        lblUsuario.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblUsuario.setText("Usuario:");
        backround.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 60, -1));

        txtUsuario.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setText("Ingresa tu nombre de Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        backround.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 170, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 153));
        backround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 180, 10));

        lblContraseña.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblContraseña.setText("Contraseña:");
        backround.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 70, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 153));
        backround.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 180, 10));

        txtPassword.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtPassword.setText("aaaaaaaa");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        backround.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 170, -1));

        jButtonEntrar.setBackground(new java.awt.Color(0, 153, 153));
        jButtonEntrar.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setText("ENTRAR");
        jButtonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEntrarMouseClicked(evt);
            }
        });
        backround.add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backround, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backround, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        while (pressedUsuario == false) {
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
            pressedUsuario = true;
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        while (pressedPass == false) {
            txtPassword.setText("");
            txtPassword.setForeground(Color.black);
            pressedPass = true;
        }
    }//GEN-LAST:event_txtPasswordMousePressed

    private void jButtonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEntrarMouseClicked
        // Este metodo captara los datos ingresados en txtUsuario y txtPassword
        // para su validaion
        // Aqui se programara la autenticacion del usuario
        Usuario objUsuario = new Usuario();
        objUsuario.setUsuario(txtUsuario.getText());
        objUsuario.setPassword(new String(txtPassword.getPassword()));

        //validando al usuario contra la base de datos
        if (this.validarUsuario(objUsuario)) {
            //si el usuario es valido
            try (Connection conn = new ConexionBD().conexionDataBase()) {
                guiutmedic.clases.PerfilBD perfilDB = new guiutmedic.clases.PerfilBD(); // Asegúrate de importar bien
                int idPerfil = perfilDB.obtenerIdPerfilPorIdUsuario(conn, objUsuario.getIdUsuario());

                objUsuario.setIdPerfil(idPerfil);

        JOptionPane.showMessageDialog(this, "Bienvenido a UTMEDIC, " + objUsuario.getUsuario() + "!"); //Bienvenida + nombre del usuario

                // Se oculta esta ventana
                this.setVisible(false);
                // Se construye el menú principal con el usuario completo
                frmMenuPrincipal menuPrincipal = new frmMenuPrincipal(objUsuario);
                menuPrincipal.setVisible(true);
                this.dispose();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error en login: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
        }
    }//GEN-LAST:event_jButtonEntrarMouseClicked

    public boolean validarUsuario(Usuario objUsuario) {
        boolean accesoPermitido = false;
        Connection conn;
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            ConexionBD objetoConexionBD = new ConexionBD();
            conn = objetoConexionBD.conexionDataBase();
            UsuarioBD bd = new UsuarioBD();

            rs = bd.consultarUsuarioLogin(conn, objUsuario.getUsuario(), objUsuario.getPassword());

            if (rs.next()) {  // Encontró al usuario
                objUsuario.setRol(rs.getString("rol"));
                objUsuario.setIdUsuario(rs.getInt("idusuario"));
                objUsuario.setMatricula(rs.getString("matricula"));
                accesoPermitido = true;

                System.out.println("Usuario validado: id=" + objUsuario.getIdUsuario() + ", usuario=" + objUsuario.getUsuario());
            }

            // Guarda el id para uso interno si quieres
//        idUsuarioActual = rs.getInt(1);
            objetoConexionBD.cerrarConexion(conn);

        } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
            // Manejo de errores
        }

        return accesoPermitido;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backround;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
