
package guiutmedic;

import guiutmedic.clases.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import guiutmedic.clases.Usuario; // Agrega esta importación
import guiutmedic.clases.PerfilDB; // SE agrega est
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author santi
 */
public class frmHistorialCitas extends javax.swing.JInternalFrame {

    private Usuario objetoMenuP;
    private int idPerfilActual;
    
    public frmHistorialCitas(Usuario objUsuario) {
        initComponents();
        this.objetoMenuP = objUsuario;
        // Obtenemos el idPerfil al inicializar el formulario
        try {
            ConexionBD conexion = new ConexionBD();
            Connection con = conexion.conexionDataBase();
            PerfilDB perfilDB = new PerfilDB();
            this.idPerfilActual = perfilDB.obtenerIdPerfilPorIdUsuario(con, objetoMenuP.getIdUsuario());
            conexion.cerrarConexion(con);
        } catch (Exception ex) {
            Logger.getLogger(frmHistorialCitas.class.getName()).log(Level.SEVERE, null, ex);
        }
        cargarHistorial(); // Ahora el método cargarHistorial usará el idPerfilActual
    }

    
    public void cargarHistorial() {
    DefaultTableModel modeloTabla = (DefaultTableModel) tablaHistorial.getModel();
    modeloTabla.setRowCount(0); // Limpia la tabla antes de cargar datos nuevos

    try {
            ConexionBD conexion = new ConexionBD();
            Connection con = conexion.conexionDataBase();

            // Modificación aquí: la consulta ahora filtra por el IdPaciente
            String sql = "SELECT * FROM historial_citas WHERE IdPaciente = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, idPerfilActual); // Se usa el idPerfil del usuario actual
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[7];
                fila[0] = rs.getInt("IdCita");
                fila[1] = rs.getInt("IdPaciente");
                fila[2] = rs.getInt("IdPersonal");
                fila[3] = rs.getString("Profesion");
                fila[4] = rs.getDate("Fecha");
                fila[5] = rs.getString("Hora");
                fila[6] = rs.getString("MotivoConsulta");

                modeloTabla.addRow(fila);
            }

            rs.close();
            ps.close();
            conexion.cerrarConexion(con);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar historial: " + e.getMessage());
            e.printStackTrace(); // Es buena práctica imprimir el stack trace para depurar
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IdCita", "IdPaciente", "IdMedico", "Profesion", "Fecha", "Hora", "Motivo Consulta"
            }
        ));
        jScrollPane2.setViewportView(tablaHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaHistorial;
    // End of variables declaration//GEN-END:variables
}
