package guiutmedic;


import guiutmedic.clases.ConexionBD;
import guiutmedic.clases.Usuario;
import guiutmedic.clases.UsuarioBD;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class frmLoginUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmLoginUusario
     */
    public frmLoginUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backround = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblContraseña = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jpasswordUsuario = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        lblUsuario1 = new javax.swing.JLabel();
        txtUsuario1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);

        backround.setBackground(new java.awt.Color(252, 252, 252));
        backround.setToolTipText("");
        backround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenido.setFont(new java.awt.Font("Inter", 3, 14)); // NOI18N
        lblBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenido.setText("Bienvenido");
        backround.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 30));

        lblIcono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiutmedic/imagenes/icono.jpeg"))); // NOI18N
        backround.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 190));

        lblUsuario.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblUsuario.setText("Usuario:");
        backround.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, -1));

        txtUsuario.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setText("Ingresa tu nombre de Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        backround.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 170, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 153));
        backround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 180, 10));

        lblContraseña.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblContraseña.setText("Contraseña:");
        backround.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 153));
        backround.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 180, 10));

        jpasswordUsuario.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jpasswordUsuario.setBorder(null);
        jpasswordUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpasswordUsuarioMousePressed(evt);
            }
        });
        jpasswordUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordUsuarioActionPerformed(evt);
            }
        });
        backround.add(jpasswordUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 170, -1));

        jButtonEntrar.setBackground(new java.awt.Color(0, 153, 153));
        jButtonEntrar.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setText("ENTRAR");
        jButtonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEntrarMouseClicked(evt);
            }
        });
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        backround.add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        lblUsuario1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        lblUsuario1.setText("Matricula:");
        backround.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 60, -1));

        txtUsuario1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtUsuario1.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario1.setText("Ingresa tu matricula");
        txtUsuario1.setBorder(null);
        txtUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuario1MousePressed(evt);
            }
        });
        txtUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuario1ActionPerformed(evt);
            }
        });
        backround.add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 170, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 153));
        backround.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 180, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backround, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backround, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarUsuario(Usuario objUsuario) {

        //variables de clase 
        boolean accesoPermitido = false;  //variable de retorno en caso de ser falso o verdadero
        Connection conn;   // objeto de conexion
        PreparedStatement stmt = null;   // variable para la sentencia sql
        ResultSet rs = null;    //variable para resultado de consulta sql
        //aqui se conectara a la base de datos y se buscara el usuario en la tabla de usuarios del sistema para su comparacion
        try {
            ConexionBD objetoConexionBD = new ConexionBD();
            conn = objetoConexionBD.conexionDataBase();
            UsuarioBD bd = new UsuarioBD();
            rs = bd.consultarUsuarioLogin(conn, objUsuario.getUsuario(), objUsuario.getPassword(), objUsuario.getMatricula());
            if (rs.next()) {  //encontro al menos 1 registro con los datos
                //accedemos al sistema
                accesoPermitido = true;
            }
            //se cierra la conexion
            objetoConexionBD.cerrarConexion(conn);

        } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error de conexión "
                    + ex.getMessage());
        }
        //regresamos si el usuario se localizo
        return accesoPermitido;
    }
    
    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        txtUsuario.setText("");
        txtUsuario.setForeground(Color.black);
        jpasswordUsuario.setText("********");
        jpasswordUsuario.setForeground(Color.gray);
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void jpasswordUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordUsuarioActionPerformed

    private void jpasswordUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpasswordUsuarioMousePressed
       if(txtUsuario.getText().equals("Ingresa tu nombre de Usuario")){
        txtUsuario.setForeground(Color.gray);
        jpasswordUsuario.setText("");
        jpasswordUsuario.setForeground(Color.black);
    }
     if (String.valueOf(jpasswordUsuario.getPassword()).isEmpty()) {
        jpasswordUsuario.setText("*****");
         jpasswordUsuario.setForeground(Color.GRAY);
    }  
    }//GEN-LAST:event_jpasswordUsuarioMousePressed

    private void jButtonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEntrarMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this,"Bienvenido a utmedic");
    }//GEN-LAST:event_jButtonEntrarMouseClicked

    private void txtUsuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuario1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario1MousePressed

    private void txtUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLoginUsuario().setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backround;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPasswordField jpasswordUsuario;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
