
package guiutmedic;

import guiutmedic.utilerias.fondoPantallaMenu;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author santi
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    
    int idUsuarioActual;

    public int getIdUsuarioActual() {
        return idUsuarioActual;
    }

    public void setIdUsuarioActual(int idUsuarioActual) {
        this.idUsuarioActual = idUsuarioActual;
    }
    
 public frmMenuPrincipal() {
       fondoPantallaMenu fondo = new fondoPantallaMenu();
    initComponents();
    // Maximiza la ventana al iniciar
    setExtendedState(JFrame. MAXIMIZED_BOTH);
    // Establece tamaño personalizado en función del ancho de la pantalla y una altura y ancho fijos
    Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
    setSize(1160, 700);
    // Asigna imagen de fondo al panel principal (desktopPane)
    if (desktopPane != null) {
    desktopPane.setBorder(fondo); // Asegúrate de que fondo esté correctamente definido
    }
    // Establece el icono de la aplicación si la imagen existe
    try {
      ImageIcon iconoApp = new ImageIcon(getClass().getResource("/guiutmedic/imagenes/icono.jpeg"));
        setIconImage(iconoApp.getImage());
    } catch (NullPointerException e) {
    System.err.println("No se pudo cargar el icono de la aplicación: " + e.getMessage());
    }
     System.out.println("ID Usuario actual: "+idUsuarioActual);
    } 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        JmenuBar = new javax.swing.JMenuBar();
        jMenuPerfil = new javax.swing.JMenu();
        jMenuAgendar = new javax.swing.JMenu();
        jMenuReagendar = new javax.swing.JMenu();
        jMenuHistorial = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        jMenuPerfil.setText("Perfil");
        jMenuPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPerfilMouseClicked(evt);
            }
        });
        jMenuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPerfilActionPerformed(evt);
            }
        });
        JmenuBar.add(jMenuPerfil);

        jMenuAgendar.setText("Agendar");
        jMenuAgendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAgendarMouseClicked(evt);
            }
        });
        JmenuBar.add(jMenuAgendar);

        jMenuReagendar.setText("Reagendar");
        jMenuReagendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuReagendarMouseClicked(evt);
            }
        });
        JmenuBar.add(jMenuReagendar);

        jMenuHistorial.setText("Historial");
        jMenuHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHistorialMouseClicked(evt);
            }
        });
        JmenuBar.add(jMenuHistorial);

        jMenuSalir.setText("Salir");
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirMouseClicked(evt);
            }
        });
        JmenuBar.add(jMenuSalir);

        setJMenuBar(JmenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuPerfilActionPerformed

    private void jMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMouseClicked
        int opcion = JOptionPane.showConfirmDialog(this,
        "¿Estas seguro de salir?",
        "Confirmar salida de UTMEDIC",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);

    if (opcion == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_jMenuSalirMouseClicked

    private void jMenuPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPerfilMouseClicked
     try {
         frmPerfil ventanaPerfil = new frmPerfil(this);
         this.desktopPane.add(ventanaPerfil);
         ventanaPerfil.setVisible(true);
         System.out.println("ID Usuario actual: "+idUsuarioActual);
         ventanaPerfil.setIdUsuarioDeseado(idUsuarioActual);
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(frmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jMenuPerfilMouseClicked

    private void jMenuAgendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAgendarMouseClicked
        frmAgendar ventanaGUI = new frmAgendar();   
        this.desktopPane.add(ventanaGUI);
        ventanaGUI.setVisible(true);   
    }//GEN-LAST:event_jMenuAgendarMouseClicked

    private void jMenuReagendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuReagendarMouseClicked
        frmReagendar ventanaGUI = new frmReagendar();   
        this.desktopPane.add(ventanaGUI);
        ventanaGUI.setVisible(true);
    }//GEN-LAST:event_jMenuReagendarMouseClicked

    private void jMenuHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHistorialMouseClicked
        frmHistorialCitas ventanaGUI = new frmHistorialCitas();   
        this.desktopPane.add(ventanaGUI);
        ventanaGUI.setVisible(true);
    }//GEN-LAST:event_jMenuHistorialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JmenuBar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenuAgendar;
    private javax.swing.JMenu jMenuHistorial;
    private javax.swing.JMenu jMenuPerfil;
    private javax.swing.JMenu jMenuReagendar;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
